In [1]:
from pathlib import Path
import pandas as pd

CAMINHO_DADOS = Path("../data/raw/agricola/pam_cana_guariba_raw.csv")

df_raw = pd.read_csv(CAMINHO_DADOS, dtype={"NC": str})

print(f"Quantidade de linhas: {len(df_raw):,}")
print(f"Quantidade de colunas: {len(df_raw.columns)}")

df_raw.head()

Quantidade de linhas: 125
Quantidade de colunas: 15

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N,variavel_padronizada,V_numerico
0,6,Município,1006,Hectares,17000,3518602,Guariba (SP),8331,Área plantada ou destinada à colheita,2000,2000,40106,Cana-de-açúcar,area_plantada_ha,17000
1,6,Município,1006,Hectares,17000,3518602,Guariba (SP),8331,Área plantada ou destinada à colheita,2001,2001,40106,Cana-de-açúcar,area_plantada_ha,17000
2,6,Município,1006,Hectares,17000,3518602,Guariba (SP),8331,Área plantada ou destinada à colheita,2002,2002,40106,Cana-de-açúcar,area_plantada_ha,17000
3,6,Município,1006,Hectares,17000,3518602,Guariba (SP),8331,Área plantada ou destinada à colheita,2003,2003,40106,Cana-de-açúcar,area_plantada_ha,17000
4,6,Município,1006,Hectares,19000,3518602,Guariba (SP),8331,Área plantada ou destinada à colheita,2004,2004,40106,Cana-de-açúcar,area_plantada_ha,19000

In [2]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   NC                    125 non-null    str
 1   NN                    125 non-null    str
 2   MC                    125 non-null    int64
 3   MN                    125 non-null    str
 4   V                     125 non-null    int64
 5   D1C                   125 non-null    int64
 6   D1N                   125 non-null    str
 7   D2C                   125 non-null    int64
 8   D2N                   125 non-null    str
 9   D3C                   125 non-null    int64
 10  D3N                   125 non-null    int64
 11  D4C                   125 non-null    int64
 12  D4N                   125 non-null    str
 13  variavel_padronizada  125 non-null    str
 14  V_numerico            125 non-null    int64
dtypes: int64(8), str(7)
memory usage: 25.7 KB

In [3]:
print("Colunas disponíveis:")
for coluna in df_raw.columns:
    print(f"- {coluna}")

Colunas disponíveis:
- NC
- NN
- MC
- MN
- V
- D1C
- D1N
- D2C
- D2N
- D3C
- D3N
- D4C
- D4N
- variavel_padronizada
- V_numerico

In [4]:
codigo_guariba = "3518602"

df_guariba_raw = df_raw[df_raw["NC"] == codigo_guariba].copy()

print(f"Quantidade de registros de Guariba: {len(df_guariba_raw)}")

df_guariba_raw.head(20)

Quantidade de registros de Guariba: 0

Empty DataFrame
Columns: [NC, NN, MC, MN, V, D1C, D1N, D2C, D2N, D3C, D3N, D4C, D4N, variavel_padronizada, V_numerico]
Index: []